//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIO
    {
        public int ID_ESTUDIO { get; set; }
        public string DESCRIPCION_ESTUDIO { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
    
        public virtual PROFESOR PROFESOR { get; set; }
    }
}
