//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculacion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SECCION_MATERIA
    {
        //public int ID_SECCION { get; set; }
        //public int ID_MATERIA { get; set; }
        //public int ID_PROFESOR { get; set; }
        //public string HORARIO { get; set; }

        [Display(Name = "Seccion")]
        public int ID_SECCION { get; set; }
        [Display(Name = "Materia")]
        public int ID_MATERIA { get; set; }
        [Display(Name = "Profesor")]
        public int ID_PROFESOR { get; set; }
        [Display(Name = "Horario")]
        public string HORARIO { get; set; }


        public virtual MATERIA MATERIA { get; set; }
        public virtual PROFESOR PROFESOR { get; set; }
        public virtual SECCION SECCION { get; set; }
    }
}
