//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUTOR()
        {
            this.ESTUDIANTE = new HashSet<ESTUDIANTE>();
        }
    
        public string CEDULA_TUTOR { get; set; }
        public string NOMBRE_TUTOR { get; set; }
        public string APELLIDO_TUTOR { get; set; }
        public string RELACION_ESTUDIANTE { get; set; }
        public string SEXO_TUTOR { get; set; }
        public string TELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTE> ESTUDIANTE { get; set; }
    }
}
